version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/linkgate

  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=linkgate
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
